### ISSUE TITLE
Problema con HC-SR04

### ISSUE THREAD

**Issue by mgabbo** [fedemarche/MSP430-HCSR04-SONAR-PROJECT#1]
Salve ho scritto questo codice per l' mps430fr5739 con il sensore sr04, ma purtroppo non risco a visualizzare la distanza, credo che il problema sia sull'echo e sulla routine di interrupt, sapresti darmi una mano? Grazie mille.
#include <msp430.h> 

void setup_clk();
void setup_uart();
void write_string();

#define TRIG_PIN BIT0 //P1.0
#define ECHO_PIN BIT1 //P1.1

volatile unsigned long start_time;
volatile unsigned long end_time;
volatile unsigned long delta_time;
volatile unsigned long distance;

void setup_clk(){
    CSCTL0 = 0xA500;    //pw clk
    CSCTL1 |= DCORSEL;
    //CSCTL1 &= ~BIT2;  //DCO a 20MHz
    //CSCTL1 = DCOFSEL_0; //DCO a 16MHz
    CSCTL1 &= ~DCOFSEL0;    //CONTROLLARE A PAG 81 cosi 16MHz
    CSCTL1 &= ~DCOFSEL1;
    CSCTL2 |= SELA_3 | SELS_3 | SELM_3; //tutte le sorgenti collegate al DCO
    CSCTL3 = 0;
    CSCTL3 |= DIVA_4 | DIVS_0 | DIVM_0; //ACLK=DCO/16 = 1MHz
    CSCTL0_H = 0;   //blocco registri
}

void setup_uart(){
    UCA0CTL1 |= UCSWRST;    //inizializzo uart
    P2SEL1 |= BIT1 | BIT0;  //P2.0 e P2.1 come RX t TX
    UCA0BRW = 130;  //baud 9600
    UCA0MCTLW = 0X02531;
    UCA0CTL1 |= BIT7;
    UCA0CTL1 &= ~UCSWRST;
}

void init_ultrasonic_pins(void)
{
    //ECHO P1.1 input
    P1DIR &= ~ECHO_PIN;
    //P1.1 deve essere CCI0A
    P1SEL0 |= ECHO_PIN;
    P1SEL1 &= ~ECHO_PIN;

    //TRIGGER P1.0 output
    P1DIR |= TRIG_PIN;
    //TRIGGER impostato basso
    P1OUT &= ~TRIG_PIN;
    P1SEL0 &= ~TRIG_PIN;
    P1SEL1 &= ~TRIG_PIN;
}

void trig(void){
    P1OUT |= TRIG_PIN;  //trig alto
    __delay_cycles(10);    //10 per 10us
    P1OUT &= ~TRIG_PIN; //trig basso
}

void init_timer(){
    TA0CTL = MC_0; //stop timer PAG 349

    TA0CTL |= TASSEL__ACLK+MC_2+TAIE; //source ACLK e continus up

    TA0CCTL2 |= CM_3 + SCS + CCIS_0 + CAP + CCIE; //PAG 351
    /*CM_3 entrambi i fronti
     *SCS sinc con clock PAG 340
     *CCIS_0 segnale input capture CCI0A
     *CAP capture
     *CCIE interrupt enable*/
}

void reset_timer(){
    TA0CTL |= TACLR; //reset conteggio PAG 349
}

void main(void){
    WDTCTL = WDTPW | WDTHOLD;   // stop watchdog timer

    setup_clk();
    setup_uart();
    init_ultrasonic_pins();
    init_timer();

    __bis_SR_register(GIE);
    __no_operation();

    reset_timer();
    trig();

    __delay_cycles(1000000); //1sec

    while(1);
}

void write_string(unsigned volatile int dist){

    unsigned volatile long i=0;
    unsigned volatile long sens=0;
    //unsigned volatile long d=0;
    unsigned volatile char c=0x30; //0

    for(i = 1000000; i >= 1000; i = i/10){
        while(!(UCTXIFG & UCA0IFG));    //attesa disponibilità buffer
        sens=distance/i;
        c=(char)(sens+0x30);
        distance=distance-i*sens;
        UCA0TXBUF = c;  //stampa singolo carattere
    }
    while(!(UCTXIFG & UCA0IFG));    //attesa disponibilità buffer
    UCA0TXBUF = '.';
    for(i = 100; i >= 1; i=i/10){
        while(!(UCTXIFG & UCA0IFG));
        sens=distance/i;
        c=(char)(sens+0x30);
        distance=distance-i*sens;
        UCA0TXBUF = c;  //stampa singolo carattere
    }
    while(!(UCTXIFG & UCA0IFG));
    UCA0TXBUF = '\r';
    while(!(UCTXIFG & UCA0IFG));
    UCA0TXBUF = '\n';

}

#pragma vector=TIMER0_A1_VECTOR
__interrupt void misura(void){

    while(P1IN & ECHO_PIN==0);
    TA0R=0;
    start_time=0;

    while(P1IN & ECHO_PIN>0);
    delta_time=TA0R;
    distance=delta_time/58;
    write_string(distance);
    trig();
    return;
}

**Comment by fedemarche** [comment]
Ciao, 
Mi dispiace ma non è un problema inerente a questa repository. 
Potrebbe dipendere dal cablaggio del circuito o dalle specifiche rispetto alle varie porte di input del modello di MSP che stai utilizzando, quindi non posso risponderti con certezza a riguardo.

Ti consiglio di recarti sui forum dedicati della Texas Instruments dove sicuramente potranno offrirti un supporto migliore e rispondere ai tuoi dubbi.
